### ISSUE TITLE
自定义组件，js版本非ts版的怎么使用？可否给个demo。

### ISSUE THREAD

**Issue by chunnuanchuankai** [pengzhanbo/pengzhanbo.cn#49]
自定义组件，js版本非ts版的怎么使用？可否给个demo。

想要在首页自定义 浮窗组件；
![image](https://github.com/pengzhanbo/pengzhanbo.cn/assets/38777492/10f76351-4baf-440e-b2d6-d5c9dedae112)

**Comment by pengzhanbo** [comment]
自定义组件的开发遵循 [vue](https://cn.vuejs.org/guide/components/registration.html) 的开发范式，你可以直接在 `.vuepress/components` 目录中开发相关组件 （使用 js 或 ts 均可），

然后在 [`.vuepress/client.js`](https://v2.vuepress.vuejs.org/zh/guide/configuration.html#%E5%AE%A2%E6%88%B7%E7%AB%AF%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6) 中将其注册为全局组件：

```ts
import { defineClientConfig } from 'vuepress/client'
import YourComponent from './components/YourComponent.vue'

export default defineClientConfig({
  enhance({ app, router, siteData }) {
    app.component('YourComponent', YourComponent)
  },
  setup() {},
  rootComponents: [],
})
```

然后就可以在 `README.md` 文件中，直接使用该组件:

```md
---
home: true
---

<YourComponent />
```
