### ISSUE TITLE
克隆大佬的 package.json文件，下载依赖有错误

### ISSUE THREAD

**Issue by shylock-wu** [pengzhanbo/pengzhanbo.cn#51]
## 描述
因为我只复制了package.json，所以锁文件是通过`pnpm i`创建的，于是就出现了以下问题
## 截图
![CleanShot 2024-06-26 at 00 08 09@2x](https://github.com/pengzhanbo/pengzhanbo.cn/assets/73875874/0584138e-561d-4ca9-abe5-33ca3bd0beb0)

**但是我恢复锁文件，再重新下载依赖是正常的，请问这个算是一个问题吗**

**Comment by pengzhanbo** [comment]
另外有一些 被标记为 弃用的依赖是 来自于 `anywhere` 这个包，这个包的依赖年代也很久远了，甚至可以追溯都 10 年前。我在这个仓库中将其替换为了 `http-server` 来提供 构建后的本地预览服务。虽然 `http-server` 最新的包也是 2022 年不算新。
